name: flutter_ikanban_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.5.2+7

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  freezed: ^3.2.0
  json_serializable: ^6.10.0
  get_it: ^8.2.0
  drift: ^2.28.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  path: ^1.9.1
  sqlite3_flutter_libs: ^0.5.39
  freezed_annotation: ^3.1.0
  go_router: ^16.1.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  share_plus: ^10.0.3
  shared_preferences: ^2.5.3
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.28.1
  build_runner: ^2.6.0
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  test: ^1.26.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/images/screen_shots/

flutter_launcher_icons:
    android: "launcher_icon" # or true, or a custom name like "my_app_icon"
    ios: true
    image_path: "assets/icons/logo.png"

    # For adaptive icons (Android):
    adaptive_icon_foreground: "assets/icons/logo.png"
    adaptive_icon_background: "#FFFFFF"

    remove_alpha_ios: true